### ISSUE TITLE
Fix attempt to send item that is not in `waiting` state

### ISSUE THREAD

**Issue by davidfoliveira** [davidfoliveira/homeswitch-api#1]
FIX (slow connect):
```
2020-11-08 22:08:24.408117Z: [DBUG] Sending to bf4a36374de48f83d8vd9g...
2020-11-08 22:08:24.408142Z: [WARN] I was told I can process the next queued item but the item is not in 'waiting' state
```
This is possible related to slow connects or reconnects.

**Comment by davidfoliveira** [comment]
Still happening despite efforts to make it go away

**Comment by davidfoliveira** [comment]
This is likely to be related to any unhandled error occurring in the sequence of a socket IO read() or write(). However, I couldn't still understand why and how.

**Comment by davidfoliveira** [comment]
```
2020-11-15 10:52:02.534952Z: [ERRO] Error reading and parsing message: Return code is 1. An error has occurred
2020-11-15 10:52:02.534997Z: [WARN] Marking connection as unhealthy. Reconnecting and resending message!
2020-11-15 10:52:02.535046Z: [INFO] Disconnecting from Tuya device bf5d0abdb1e62...
2020-11-15 10:52:02.535088Z: [DBUG] Closing connecting socket to 192.168.10.178:6668 (fd: 6)
2020-11-15 10:52:02.535217Z: [DBUG] IP: 192.168.10.178, PORT: 6668, GW_ID: bf5d0abdb1e62
2020-11-15 10:52:02.535266Z: [INFO] Connecting to Tuya device bf5d0abdb1e62 at 192.168.10.178:6668...
2020-11-15 10:52:02.535758Z: [DBUG] Setting socket timeout to 10
2020-11-15 10:52:02.536048Z: [DBUG] Connection to Tuya device bf5d0abdb1e62 at 192.168.10.178:6668 for file descriptor 6
2020-11-15 10:52:02.536286Z: [WARN] Socket (192.168.10.178:6668) error occurred: <type 'exceptions.Exception'> The first queue message object is NOT in "sent" state. State: waiting <traceback object at 0x1058ba1b8>
2020-11-15 10:52:02.536902Z: [ERRO] Socket error on device's bf5d0abdb1e6210180duku connection: ['Traceback (most recent call last):\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 83, in read\n    obj.handle_read_event()\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 449, in handle_read_event\n    self.handle_read()\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 171, in handle_read\n    self.emit(\'read\')\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit\n    remove = [l for l in listeners if not l(*args, **kwargs)]\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__\n    self.func(*args, **kwargs)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 111, in _on_read\n    self.emit(\'data\')\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit\n    remove = [l for l in listeners if not l(*args, **kwargs)]\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__\n    self.func(*args, **kwargs)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/hw/tuya.py", line 309, in _on_dev_data\n    raise Exception(\'The first queue message object is NOT in "sent" state. State: {}\'.format(msg_obj.get(\'status\')))\n', 'Exception: The first queue message object is NOT in "sent" state. State: waiting\n']
2020-11-15 10:52:02.537083Z: [INFO] Disconnecting from Tuya device bf5d0abdb1e62...
```
