### ISSUE TITLE
Event 'connect' called when connection is actually not established (the IP doesn't exist)

### ISSUE THREAD

**Issue by davidfoliveira** [davidfoliveira/homeswitch-api#10]
```
2020-11-13 06:23:22.694746Z: [INFO] Connection to 192.168.11.178:6668 was reset by peer.
2020-11-13 06:23:22.694818Z: [INFO] Device bf5d0abdb1e62 has disconnected.
2020-11-13 06:23:22.694856Z: [INFO] Reconnecting to bf5d0abdb1e62...
2020-11-13 06:23:22.694891Z: [INFO] Disconnecting from device bf5d0abdb1e62...
2020-11-13 06:23:22.694933Z: [DBUG] Closing connecting socket to 192.168.11.178:6668 (fd: 5)
2020-11-13 06:23:22.695017Z: [DBUG] IP: 192.168.11.178, PORT: 6668, GW_ID: bf5d0abdb1e62
2020-11-13 06:23:22.695056Z: [INFO] Connecting to device bf5d0abdb1e62 at 192.168.11.178:6668...
2020-11-13 06:23:22.695250Z: [DBUG] Setting socket timeout to 2
2020-11-13 06:23:24.698955Z: [INFO] Connected to 192.168.11.178:6668 !
2020-11-13 06:23:24.699072Z: [INFO] Connected to device bf5d0abdb1e62 !
2020-11-13 06:23:24.699140Z: [DBUG] We can send next command for bf5d0abdb1e62!!!
2020-11-13 06:23:24.699175Z: [DBUG] Sending to bf5d0abdb1e62...
2020-11-13 06:23:24.702780Z: [DBUG] Sending 183 bytes to 192.168.11.178:6668 (fd: 5)
2020-11-13 06:23:26.705013Z: [WARN] Socket (192.168.11.178:6668) error occurred: <class 'socket.timeout'> timed out <traceback object at 0x1036e9cb0>
2020-11-13 06:23:26.707105Z: [ERRO] Socket error on device's bf5d0abdb1e62 connection: ['Traceback (most recent call last):\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 91, in write\n    obj.handle_write_event()\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 467, in handle_write_event\n    self.handle_connect_event()\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 455, in handle_connect_event\n    self.handle_connect()\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 109, in handle_connect\n    self.emit(\'connect\')\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit\n    remove = [l for l in listeners if not l(*args, **kwargs)]\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__\n    self.func(*args, **kwargs)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 65, in _on_connect\n    self.emit(\'connect\')\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit\n    remove = [l for l in listeners if not l(*args, **kwargs)]\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__\n    self.func(*args, **kwargs)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/hw/tuya.py", line 219, in _on_dev_connect\n    self.emit(\'_next\')\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit\n    remove = [l for l in listeners if not l(*args, **kwargs)]\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__\n    self.func(*args, **kwargs)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/hw/tuya.py", line 138, in _on_can_send_next_command\n    self.connection.send(bin_message)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 56, in send\n    self.socket.send(data)\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 374, in send\n    result = self.socket.send(data)\n', 'timeout: timed out\n']
```

**Comment by davidfoliveira** [comment]
```
2020-11-13 06:25:11.649997Z: [WARN] Socket (192.168.11.182:6668) error occurred: <class 'socket.error'> [Errno 60] Operation timed out <traceback object at 0x105886b90>
2020-11-13 06:25:11.767504Z: [ERRO] Socket error on device's bf4a36374de connection: ['Traceback (most recent call last):\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 83, in read\n    obj.handle_read_event()\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 446, in handle_read_event\n    self.handle_connect_event()\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 454, in handle_connect_event\n    raise socket.error(err, _strerror(err))\n', 'error: [Errno 60] Operation timed out\n']
2020-11-13 06:25:11.767599Z: [INFO] Disconnecting from device bf4a36374de...
2020-11-13 06:25:11.767863Z: [INFO] Connected to 192.168.11.182:6668 !
2020-11-13 06:25:11.768031Z: [INFO] Connected to device bf4a36374de !
  File "bin/hsapid", line 7, in <module>
    main()
  File "/Users/david/projects/homeswitch-api/homeswitch/api.py", line 127, in main
    api.run()
  File "/Users/david/projects/homeswitch-api/homeswitch/api.py", line 110, in run
    asyncorepp.loop()
  File "/Users/david/projects/homeswitch-api/homeswitch/asyncorepp.py", line 22, in loop
    poll_fun(timeout, map)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 162, in poll
    write(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 91, in write
    obj.handle_write_event()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 467, in handle_write_event
    self.handle_connect_event()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 455, in handle_connect_event
    self.handle_connect()
  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 109, in handle_connect
    self.emit('connect')
  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit
    remove = [l for l in listeners if not l(*args, **kwargs)]
  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__
    self.func(*args, **kwargs)
  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 65, in _on_connect
    self.emit('connect')
  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit
    remove = [l for l in listeners if not l(*args, **kwargs)]
  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__
    self.func(*args, **kwargs)
  File "/Users/david/projects/homeswitch-api/homeswitch/hw/tuya.py", line 218, in _on_dev_connect
    traceback.print_stack()
2020-11-13 06:25:11.926305Z: [DBUG] We can send next command for bf4a36374de!!!
```
