### ISSUE TITLE
Ignore certain send() exceptions

### ISSUE THREAD

**Issue by davidfoliveira** [davidfoliveira/homeswitch-api#12]
```
2020-11-13 06:50:24.368618Z: [INFO] Client 5 crashed
2020-11-13 06:50:24.368680Z: [DEBUG] Exception
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/Users/david/projects/homeswitch-api/homeswitch/hybridserver.py", line 89, in handle_read
    self.request.push_data(data)
  File "/Users/david/projects/homeswitch-api/homeswitch/hybridserver.py", line 196, in push_data
    self._eat_raw_request()
  File "/Users/david/projects/homeswitch-api/homeswitch/hybridserver.py", line 221, in _eat_raw_request
    return self._eat_request_body(last_crlf)
  File "/Users/david/projects/homeswitch-api/homeswitch/hybridserver.py", line 240, in _eat_request_body
    self.emit('ready')
  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit
    remove = [l for l in listeners if not l(*args, **kwargs)]
  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__
    self.func(*args, **kwargs)
  File "/Users/david/projects/homeswitch-api/homeswitch/hybridserver.py", line 83, in <lambda>
    self.request.on('ready', lambda: self.emit('request', self.request, False))
  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit
    remove = [l for l in listeners if not l(*args, **kwargs)]
  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__
    self.func(*args, **kwargs)
  File "/Users/david/projects/homeswitch-api/homeswitch/hybridserver.py", line 70, in process_request
    self.server.emit('request', self, request, error)
  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit
    remove = [l for l in listeners if not l(*args, **kwargs)]
  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__
    self.func(*args, **kwargs)
  File "/Users/david/projects/homeswitch-api/homeswitch/api.py", line 49, in on_request
    return self.on_http_request(client, req, error)
  File "/Users/david/projects/homeswitch-api/homeswitch/api.py", line 79, in on_http_request
    client.message({'error': 'not_found'})
  File "/Users/david/projects/homeswitch-api/homeswitch/hybridserver.py", line 113, in message
    self.send_http(HTTP_STATUS_BY_ERROR.get(body.get('error'), 500), body)
  File "/Users/david/projects/homeswitch-api/homeswitch/hybridserver.py", line 132, in send_http
    self.send(response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 550, in send
    self.initiate_send()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 537, in initiate_send
    num_sent = dispatcher.send(self, self.out_buffer[:512])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 374, in send
    result = self.socket.send(data)
error: [Errno 41] Protocol wrong type for socket
```

**Comment by davidfoliveira** [comment]
This should be done not only in `hybridserver.py` but also in `client.py`
