### ISSUE TITLE
Understand `Resource temporarily unavailable` error during socket read()

### ISSUE THREAD

**Issue by davidfoliveira** [davidfoliveira/homeswitch-api#13]
```
2020-11-14 10:42:12.306371Z: [INFO] Getting device bf5d0abdb1e62 status
2020-11-14 10:42:12.306439Z: [DBUG] Getting Tuya device status (IP: 192.168.10.178, PORT: 6668, GW_ID: bf5d0abdb1e62)
2020-11-14 10:42:12.306505Z: [INFO] Getting device bf4a36374de48 status
2020-11-14 10:42:12.306528Z: [WARN] Device bf4a36374de48 is not online. Cannot get its status
2020-11-14 10:42:12.306837Z: [ERRO] Error getting device statuses:  bf4a36374de48
2020-11-14 10:42:12.388960Z: [INFO] Connected to 192.168.10.178:6668 !
2020-11-14 10:42:12.389063Z: [INFO] Connected to Tuya device bf5d0abdb1e62 !
2020-11-14 10:42:12.389110Z: [DBUG] We can send next command for bf5d0abdb1e62!!!
2020-11-14 10:42:12.389172Z: [DBUG] Sending to bf5d0abdb1e62...
2020-11-14 10:42:12.391450Z: [DBUG] Sending 183 bytes to 192.168.10.178:6668 (fd: 6)
2020-11-14 10:42:12.916375Z: [INFO] Socket (192.168.10.178:6668) read can happen
2020-11-14 10:42:12.916468Z: [INFO] Socket for device's bf5d0abdb1e62 has data and should be read
2020-11-14 10:42:12.916557Z: [DBUG] Got header (prefix: 21930, seq: 0, cmd: 8, size: 75)
2020-11-14 10:42:12.917526Z: [DBUG] Got device bf5d0abdb1e62 status: {u'dps': {u'1': True}, u't': 1605350531}
2020-11-14 10:42:12.917623Z: [INFO] Got a status update about device bf5d0abdb1e62. Device status has NOT changed (True)
2020-11-14 10:42:12.917660Z: [INFO] Device bf5d0abdb1e62 status is True
2020-11-14 10:42:12.917713Z: [DBUG] We can send next command for bf5d0abdb1e62!!!
2020-11-14 10:42:12.917752Z: [DBUG] Sending to bf5d0abdb1e62...
2020-11-14 10:42:12.919566Z: [DBUG] Sending 183 bytes to 192.168.10.178:6668 (fd: 6)
2020-11-14 10:42:12.919728Z: [DBUG] Got header (prefix: 21930, seq: 0, cmd: 7, size: 12)
2020-11-14 10:42:12.919958Z: [WARN] Socket (192.168.10.178:6668) error occurred: <class 'socket.error'> [Errno 35] Resource temporarily unavailable <traceback object at 0x10df67d88>
2020-11-14 10:42:12.924052Z: [ERRO] Socket error on device's bf5d0abdb1e62 connection: ['Traceback (most recent call last):\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 83, in read\n    obj.handle_read_event()\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 449, in handle_read_event\n    self.handle_read()\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 160, in handle_read\n    self.emit(\'read\')\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit\n    remove = [l for l in listeners if not l(*args, **kwargs)]\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__\n    self.func(*args, **kwargs)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 107, in _on_read\n    self.emit(\'data\')\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit\n    remove = [l for l in listeners if not l(*args, **kwargs)]\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__\n    self.func(*args, **kwargs)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/hw/tuya.py", line 267, in _on_dev_data\n    reply = self._read_and_parse_message()\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/hw/tuya.py", line 386, in _read_and_parse_message\n    header = self._read_need(16)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/hw/tuya.py", line 465, in _read_need\n    data = self.connection.receive(num_bytes)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 70, in receive\n    return self.socket.recv(num_bytes)\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 387, in recv\n    data = self.socket.recv(buffer_size)\n', 'error: [Errno 35] Resource temporarily unavailable\n']
2020-11-14 10:42:12.924506Z: [INFO] Disconnecting from Tuya device bf5d0abdb1e62...
```

**Comment by davidfoliveira** [comment]
This is because of the `while self.connected:` in `_on_dev_data()` which reads until it starts failing. We should read when `_on_dev_data()` is called instead.
