### ISSUE TITLE
Cancel command timeout in case of socket error

### ISSUE THREAD

**Issue by davidfoliveira** [davidfoliveira/homeswitch-api#17]
```
2020-11-18 22:10:32.872914Z: [WARN] Socket (127.0.0.1:6668) error occurred: <class 'socket.error'> [Errno 61] Connection refused <traceback object at 0x102e605f0>
2020-11-18 22:10:32.873807Z: [ERRO] Socket error on device's bf5d0abdb1e62 connection: ['Traceback (most recent call last):\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 91, in write\n    obj.handle_write_event()\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 467, in handle_write_event\n    self.handle_connect_event()\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 454, in handle_connect_event\n    raise socket.error(err, _strerror(err))\n', 'error: [Errno 61] Connection refused\n']
2020-11-18 22:10:32.874096Z: [INFO] Disconnecting from Tuya device bf5d0abdb1e62...
.....
2020-11-18 22:10:35.939561Z: [WARN] Trying to cancel timeout timer d7a71a0f-97a5-4f48-9890-84cfd4e01116 which doesn't exist. This should be fixed
2020-11-18 22:10:35.939730Z: [ERRO] Error getting Tuya device bf5d0abdb1e62 status: {'descriptor': 'Waited too long for the device to respond', 'error': 'command_timeout'}
```

**Comment by davidfoliveira** [comment]
This is kind of expected because connect() retries might happen. However, in case they don't happen this command should just be aborted.
