### ISSUE TITLE
Check `[Errno 64] EHOSTDOWN` issue on connect()

### ISSUE THREAD

**Issue by davidfoliveira** [davidfoliveira/homeswitch-api#4]
CHECK:
```
2020-11-10 20:44:44.846828Z: [INFO] Connecting to device bf5d0abdb1e6210180duku at 192.168.10.179:6668...
2020-11-10 20:44:44.847335Z: [WARN] Socket (192.168.10.179:6668) error occurred: <class 'socket.error'> [Errno 64] EHOSTDOWN <traceback object at 0x10541b7e8>
2020-11-10 20:44:44.848645Z: [ERRO] Socket error on device's bf5d0abdb1e6210180duku connection: ['Traceback (most recent call last):\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 83, in read\n    obj.handle_read_event()\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 446, in handle_read_event\n    self.handle_connect_event()\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 455, in handle_connect_event\n    self.handle_connect()\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 104, in handle_connect\n    self.emit(\'connect\')\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit\n    remove = [l for l in listeners if not l(*args, **kwargs)]\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__\n    self.func(*args, **kwargs)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 61, in _on_connect\n    self.emit(\'connect\')\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit\n    remove = [l for l in listeners if not l(*args, **kwargs)]\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__\n    self.func(*args, **kwargs)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/hw/tuya.py", line 201, in _on_dev_connect\n    self.emit(\'_next\')\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit\n    remove = [l for l in listeners if not l(*args, **kwargs)]\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__\n    self.func(*args, **kwargs)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/hw/tuya.py", line 127, in _on_can_send_next_command\n    self.connection.send(bin_message)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 52, in send\n    self.socket.send(data)\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 380, in send\n    self.handle_close()\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 108, in handle_close\n    self.emit(\'close\')\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit\n    remove = [l for l in listeners if not l(*args, **kwargs)]\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__\n    self.func(*args, **kwargs)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 67, in _on_close\n    self.emit(\'break\')\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit\n    remove = [l for l in listeners if not l(*args, **kwargs)]\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__\n    self.func(*args, **kwargs)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/hw/tuya.py", line 207, in _on_dev_connection_break\n    self._reconnect()\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/hw/tuya.py", line 196, in _reconnect\n    self._connect()\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/hw/tuya.py", line 182, in _connect\n    self.connection.connect(self.ip, self.port, timeout=self.socket_timeout)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 42, in connect\n    self.socket.start()\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 100, in start\n    self.connect((self._host, self._port))\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 356, in connect\n    raise socket.error(err, errorcode[err])\n', 'error: [Errno 64] EHOSTDOWN\n']
```

Happening at the same time as other timeouts and instability events.

**Comment by davidfoliveira** [comment]
Should have been fixed by https://github.com/davidfoliveira/homeswitch-api/commit/ecf43adb0dff10396457fa4f35c80576476f40e6
