### ISSUE TITLE
Check `Connection reset by peer` and handle it

### ISSUE THREAD

**Issue by davidfoliveira** [davidfoliveira/homeswitch-api#5]
```
2020-11-10 20:45:09.098546Z: [WARN] Socket (192.168.10.179:6668) error occurred: <class 'socket.error'> [Errno 54] Connection reset by peer <traceback object at 0x10531bb90>
2020-11-10 20:45:09.098956Z: [ERRO] Socket error on device's bf5d0abdb1e6210180duku connection: ['Traceback (most recent call last):\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 83, in read\n    obj.handle_read_event()\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 446, in handle_read_event\n    self.handle_connect_event()\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 454, in handle_connect_event\n    raise socket.error(err, _strerror(err))\n', 'error: [Errno 54] Connection reset by peer\n']
```

Happening at the same time as other instability events

**Comment by davidfoliveira** [comment]
This was due to incorrect calling of `handle_connect()` via `read()` or `write()` due to `readable()` and `writable` returning `True` by default. Check #10
