### ISSUE TITLE
Check issue with slow connects

### ISSUE THREAD

**Issue by davidfoliveira** [davidfoliveira/homeswitch-api#9]
```
2020-11-12 22:17:06.610376Z: [INFO] Updating device bf5d0abdb1e62 status...
2020-11-12 22:17:06.610463Z: [INFO] Getting device bf5d0abdb1e62 status
2020-11-12 22:17:06.610529Z: [DBUG] Getting device status (IP: 192.168.10.178, PORT: 6668, GW_ID: bf5d0abdb1e62)
...
2020-11-12 22:17:18.591902Z: [WARN] Socket (192.168.10.178:6668) error occurred: <class 'socket.error'> [Errno 60] Operation timed out <traceback object at 0x10c37bf38>
2020-11-12 22:17:18.592588Z: [ERRO] Socket error on device's bf5d0abdb1e62 connection: ['Traceback (most recent call last):\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 83, in read\n    obj.handle_read_event()\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 446, in handle_read_event\n    self.handle_connect_event()\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 454, in handle_connect_event\n    raise socket.error(err, _strerror(err))\n', 'error: [Errno 60] Operation timed out\n']
2020-11-12 22:17:18.592641Z: [INFO] Disconnecting from device bf5d0abdb1e62...
2020-11-12 22:17:18.592718Z: [INFO] Connected to 192.168.10.178:6668 !
2020-11-12 22:17:18.592753Z: [INFO] Connected to device bf5d0abdb1e62 !
2020-11-12 22:17:18.620466Z: [DBUG] We can send next command for bf5d0abdb1e62!!!
2020-11-12 22:17:18.620543Z: [DBUG] Sending to bf5d0abdb1e62...
2020-11-12 22:17:18.620581Z: [WARN] I was told I can process the next queued item but the item is not in 'waiting' state
2020-11-12 22:17:18.620821Z: [INFO] Socket (192.168.10.178:6668) read can happen
2020-11-12 22:17:18.620872Z: [INFO] Socket for device's bf5d0abdb1e62 has data and should be read
2020-11-12 22:17:18.620960Z: [INFO] Connection to 192.168.10.178:6668 was closed.
2020-11-12 22:17:18.620990Z: [INFO] Connection to 192.168.10.178:6668 was reset by peer.
2020-11-12 22:17:18.621037Z: [INFO] Device bf5d0abdb1e62 has disconnected.
2020-11-12 22:17:18.621066Z: [INFO] Reconnecting to bf5d0abdb1e62...
2020-11-12 22:17:18.621093Z: [INFO] Disconnecting from device bf5d0abdb1e62...
2020-11-12 22:17:18.621122Z: [DBUG] Closing connecting socket to 192.168.10.178:6668 (fd: 5)
2020-11-12 22:17:18.621188Z: [DBUG] IP: 192.168.10.178, PORT: 6668, GW_ID: bf5d0abdb1e62
2020-11-12 22:17:18.621218Z: [INFO] Connecting to device bf5d0abdb1e62 at 192.168.10.178:6668...
2020-11-12 22:17:20.625431Z: [INFO] Connected to 192.168.10.178:6668 !
2020-11-12 22:17:20.625551Z: [INFO] Connected to device bf5d0abdb1e62 !
2020-11-12 22:17:20.625616Z: [DBUG] We can send next command for bf5d0abdb1e62!!!
2020-11-12 22:17:20.625644Z: [DBUG] Sending to bf5d0abdb1e62...
2020-11-12 22:17:20.628311Z: [DBUG] Sending 183 bytes to 192.168.10.178:6668 (fd: 5)
2020-11-12 22:17:22.632660Z: [WARN] Socket (192.168.10.178:6668) error occurred: <class 'socket.timeout'> timed out <traceback object at 0x10c390908>
2020-11-12 22:17:22.633360Z: [ERRO] Socket error on device's bf5d0abdb1e62 connection: ['Traceback (most recent call last):\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 91, in write\n    obj.handle_write_event()\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 467, in handle_write_event\n    self.handle_connect_event()\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 455, in handle_connect_event\n    self.handle_connect()\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 115, in handle_connect\n    self.emit(\'connect\')\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit\n    remove = [l for l in listeners if not l(*args, **kwargs)]\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__\n    self.func(*args, **kwargs)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 67, in _on_connect\n    self.emit(\'connect\')\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit\n    remove = [l for l in listeners if not l(*args, **kwargs)]\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__\n    self.func(*args, **kwargs)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/hw/tuya.py", line 214, in _on_dev_connect\n    self.emit(\'_next\')\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 282, in emit\n    remove = [l for l in listeners if not l(*args, **kwargs)]\n', '  File "/Users/david/projects/homeswitch-api/env/lib/python2.7/site-packages/pymitter/__init__.py", line 310, in __call__\n    self.func(*args, **kwargs)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/hw/tuya.py", line 138, in _on_can_send_next_command\n    self.connection.send(bin_message)\n', '  File "/Users/david/projects/homeswitch-api/homeswitch/asyncsocket/client.py", line 58, in send\n    self.socket.send(data)\n', '  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 374, in send\n    result = self.socket.send(data)\n', 'timeout: timed out\n']
2020-11-12 22:17:22.670159Z: [INFO] Disconnecting from device bf5d0abdb1e62...
2020-11-12 22:17:22.670234Z: [DBUG] Closing connecting socket to 192.168.10.178:6668 (fd: 5)
```

Weird thing:
- Disconnecting..
- Connected!

**Comment by davidfoliveira** [comment]
Addressed by #10
